services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: llm-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - .env
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-batch-size: "400"
    networks:
      - aio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  aio-network:
    external: true
