global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
  - job_name: "vllm-api"
    static_configs:
      - targets: ["vllm:8000"]
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8001"]
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]