services:
  loki:
    image: grafana/loki:latest
    container_name: aivn-loki
    volumes:
      - ./loki/config.yml:/etc/loki/local-config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "3100:3100"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    networks:
      - aio-network

  prometheus:
    image: prom/prometheus:latest
    container_name: aivn-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    networks:
      - aio-network


  grafana:
    image: grafana/grafana:latest
    container_name: aivn-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    networks:
      - aio-network

networks:
  aio-network:
    external: true

volumes:
  grafana-storage: {}